// todo_react/src/App.js
import { useState } from 'react'
import './App.css'

function App () {
  // Il faut savoir que react à une certaine nomenclature à suivre  que vous avez dû voir sur la doc

  // Ici on crée des states pour gérer le contenu d'une tâche et "les tâches" elles même
  // On utilise la méthode useState
  const [todo, setTodo] = useState('')
  const [todoList, setTodoList] = useState([])

  // La fonction qui permet de conserver les lettre entrées dans l'input
  const handleChange = e => {
    setTodo(e.target.value)
  }

  // La fonction qui permet d'ajouter une tâche à notre liste de tâches
  const addItem = () => {
    setTodoList(prevState => [...prevState, todo])
    setTodo('')
  }
  // La fonction qui permet de supprimer une tâche  de liste de tâches
  const deleteTodo = index => {
    todoList.splice(index, 1); // On retire l'élément que l'on veut supprimer
    setTodoList([...todoList]); // Et on met à jour notre state (notre liste ici)
  }

  return (
    <div className='App'>
      <header className='App-header'>
        <h1>React ToDo List</h1>
      </header>
      <div>
        {/* On appelle notre fonction handleChange à chaque lettre entrée grâce à la méthode onChange */}
        <input value={todo} type='text' name='' id='' onChange={handleChange} />
        {/* On appelle notre fonction addItem lorsque l'on clique sur le boutton grâce à la méthode onClick */}
        <button onClick={addItem}> Créer la tâche</button>
      </div>
      {/* Ici affiche notre liste de tâche */}
      {todoList.map((e, idx) => (
        // La clé permet à React de bien afficher les bon éléménts avec la meilleur performance possible
          <div key={idx}>
            <span>{e}</span>
            {/* Grâce à la méthode onClick on appelle la fonction deleteTodo */}
            <button onClick={deleteTodo}>x</button>
          </div>
        ))}
    </div>
  )
}

export default App

// todo_angular/src/app/app.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  //Add user Input : https://angular.io/guide/user-input
  // (ctrl + f sur "Get user input from a template reference variable" pour voir l'explication)

  // Ici j'ai mon textContent qui prend la valeur de mon input
  @Input() textContent: string = "";
  // J'ai ma liste de todos qui est vide au départ
  listOfTodos: string[] = [];

// J'ai mon titre de l'application que j'ai utilisé sur ma vu pur me tester le fonctionnement des variables dans Angular
  title = 'todo_angular';

  // Ma fonction qui me permet de mettre à jour mon textContent à chaque lettre taper
  handleChange(text: string) {
    this.textContent += text;
  }

  // Ma fonction qui me permet d'ajouter ma nouvelle tâche à ma list
  addItem(todo: string) {
    this.listOfTodos.push(todo)
  }

  // Ma fonction qui me permet de supprimer ma tâche
  deleteTodo(index: number) {
    this.listOfTodos.splice(index, 1);
  }
}

<style>
  .app {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
</style>
<div class="app">
  <h1>{{ title }}</h1>
  <div>
  <!-- Mon input avec ma variable de référence #todo_content qui m'aide à récuper que la valeur de mon text la valeur
    ma méthode handleChange qui récupère chaque lettre   -->
    <input type="text" #todo_content (change)="handleChange(todo_content.value)">
    <!-- Mon button qui ajoute ma tâche à ma liste de tâche, faire attention à la valeur de mon #todo_content -->
    <!-- Ensuite dans ma méthode click toujours je réinitialise la valeur de mon input avec todo_content.value = '' -->
    <button (click)="addItem(todo_content.value); todo_content.value = ''">Ajouter une tâche</button>
  </div>
  <!-- Ici je fais un map sur ma liste de todos et affiche chaque éléménts avec un boutton pour le supprimer -->
  <div class="list" *ngFor="let todo of listOfTodos; let index = index">
    <span>{{todo}}</span>
    <!--  J'ai mon boutton qui me permet de supprimer mon éléement en lui passant l'index en paramètre -->
    <button (click)="deleteTodo(index)">x</button>
  </div>
</div>
